import type { Vehicle, GuestPass, ActivityEntry, Notification, FamilyMember, ParkingSpot, User, Unit } from './types'

export const userUnits: Unit[] = [
  {
    id: 'unit-1',
    unit: '7B',
    building: 'Building 3',
    compound: 'SODIC East',
    compoundId: 'sodic-east',
    isDefault: true,
    parkingAllowance: 4,
    parkingUsed: 2,
  },
  {
    id: 'unit-2',
    unit: '12A',
    building: 'Building 7',
    compound: 'SODIC East',
    compoundId: 'sodic-east',
    isDefault: false,
    parkingAllowance: 2,
    parkingUsed: 1,
  },
  {
    id: 'unit-3',
    unit: '3C',
    building: 'Villa Row 2',
    compound: 'Madinaty B12',
    compoundId: 'madinaty-b12',
    isDefault: false,
    parkingAllowance: 3,
    parkingUsed: 0,
  },
]

export const currentUser: User = {
  id: 'u1',
  name: 'Ahmed Hassan',
  phone: '+20 100 123 4567',
  email: 'ahmed.hassan@email.com',
  unit: '7B',
  building: 'Building 3',
  compound: 'SODIC East',
  memberSince: '2022-03-15',
  units: userUnits,
  activeUnitId: 'unit-1',
}

export const vehicles: Vehicle[] = [
  {
    id: 'v1',
    plate: 'أ ب ج 1234',
    make: 'Toyota',
    model: 'Camry',
    color: 'White',
    year: 2022,
    type: 'car',
    isPrimary: true,
    sticker: 'KMP-347',
    lastSeen: '2 hours ago',
    status: 'active',
  },
  {
    id: 'v2',
    plate: 'د هـ و 5678',
    make: 'Hyundai',
    model: 'Tucson',
    color: 'Silver',
    year: 2021,
    type: 'suv',
    isPrimary: false,
    sticker: 'KMP-348',
    lastSeen: 'Yesterday',
    status: 'active',
  },
  {
    id: 'v3',
    plate: 'ز ح ط 9012',
    make: 'Honda',
    model: 'CB500',
    color: 'Black',
    year: 2023,
    type: 'motorcycle',
    isPrimary: false,
    sticker: 'KMP-349',
    lastSeen: '3 days ago',
    status: 'active',
  },
]

export const guestPasses: GuestPass[] = [
  {
    id: 'gp1',
    guestName: 'Mohamed Ali',
    purpose: 'Family Visit',
    validFrom: '2026-03-01',
    validTo: '2026-03-31',
    maxVisits: 10,
    usedVisits: 3,
    status: 'active',
    qrCode: 'KMP-GP-2026-001-XK9',
    vehicle: 'أ ب ج 5050',
    createdAt: '2026-03-01T10:00:00',
    notes: 'Brother visiting from Alexandria',
  },
  {
    id: 'gp2',
    guestName: 'Sara Ibrahim',
    purpose: 'Contractor',
    validFrom: '2026-03-06',
    validTo: '2026-03-06',
    maxVisits: 1,
    usedVisits: 0,
    status: 'active',
    qrCode: 'KMP-GP-2026-002-YM4',
    createdAt: '2026-03-06T08:00:00',
    notes: 'Plumber for unit 7B',
  },
  {
    id: 'gp3',
    guestName: 'Khalid Mostafa',
    purpose: 'Social Visit',
    validFrom: '2026-02-15',
    validTo: '2026-02-28',
    maxVisits: 5,
    usedVisits: 5,
    status: 'expired',
    qrCode: 'KMP-GP-2026-003-ZR7',
    createdAt: '2026-02-15T09:00:00',
  },
  {
    id: 'gp4',
    guestName: 'Layla Nour',
    purpose: 'Regular Visitor',
    validFrom: '2026-03-05',
    validTo: '2026-04-05',
    maxVisits: 20,
    usedVisits: 1,
    status: 'active',
    qrCode: 'KMP-GP-2026-004-AB2',
    vehicle: 'ي ك ل 3322',
    createdAt: '2026-03-05T14:00:00',
  },
]

export const activityEntries: ActivityEntry[] = [
  {
    id: 'a1',
    type: 'entry',
    description: 'Vehicle entered via Main Gate',
    timestamp: '2026-03-06T13:45:00',
    gate: 'Main Gate',
    vehicle: 'أ ب ج 1234 — Toyota Camry',
    status: 'success',
  },
  {
    id: 'a2',
    type: 'pass_used',
    description: 'Guest pass used',
    timestamp: '2026-03-06T11:30:00',
    gate: 'Side Gate',
    person: 'Mohamed Ali',
    status: 'success',
    details: 'Family Visit — Pass KMP-GP-001',
  },
  {
    id: 'a3',
    type: 'exit',
    description: 'Vehicle exited via Main Gate',
    timestamp: '2026-03-06T09:15:00',
    gate: 'Main Gate',
    vehicle: 'أ ب ج 1234 — Toyota Camry',
    status: 'success',
  },
  {
    id: 'a4',
    type: 'visitor',
    description: 'Visitor check-in at reception',
    timestamp: '2026-03-05T17:00:00',
    gate: 'Reception',
    person: 'Layla Nour',
    status: 'success',
  },
  {
    id: 'a5',
    type: 'vehicle_flagged',
    description: 'Unknown vehicle attempted entry',
    timestamp: '2026-03-05T14:22:00',
    gate: 'Main Gate',
    vehicle: 'م ن س 8888',
    status: 'denied',
    details: 'Vehicle not registered to any unit',
  },
  {
    id: 'a6',
    type: 'entry',
    description: 'Vehicle entered via Side Gate',
    timestamp: '2026-03-05T12:10:00',
    gate: 'Side Gate',
    vehicle: 'د هـ و 5678 — Hyundai Tucson',
    status: 'success',
  },
  {
    id: 'a7',
    type: 'exit',
    description: 'Vehicle exited via Main Gate',
    timestamp: '2026-03-04T19:30:00',
    gate: 'Main Gate',
    vehicle: 'د هـ و 5678 — Hyundai Tucson',
    status: 'success',
  },
  {
    id: 'a8',
    type: 'pass_used',
    description: 'Guest pass used',
    timestamp: '2026-03-04T11:00:00',
    gate: 'Main Gate',
    person: 'Mohamed Ali',
    status: 'success',
  },
]

export const notifications: Notification[] = [
  {
    id: 'n1',
    title: 'Vehicle Entered',
    body: 'Your Toyota Camry (أ ب ج 1234) entered via Main Gate',
    type: 'entry',
    read: false,
    timestamp: '2026-03-06T13:45:00',
  },
  {
    id: 'n2',
    title: 'Guest Pass Used',
    body: 'Mohamed Ali used your guest pass at Side Gate',
    type: 'pass',
    read: false,
    timestamp: '2026-03-06T11:30:00',
  },
  {
    id: 'n3',
    title: 'Security Alert',
    body: 'An unregistered vehicle attempted entry at Main Gate',
    type: 'security',
    read: false,
    timestamp: '2026-03-05T14:22:00',
  },
  {
    id: 'n4',
    title: 'Guest Pass Expiring',
    body: 'Pass for Khalid Mostafa expires tomorrow',
    type: 'pass',
    read: true,
    timestamp: '2026-03-05T08:00:00',
  },
  {
    id: 'n5',
    title: 'Vehicle Exited',
    body: 'Your Hyundai Tucson (د هـ و 5678) exited via Main Gate',
    type: 'exit',
    read: true,
    timestamp: '2026-03-04T19:30:00',
  },
  {
    id: 'n6',
    title: 'New Feature Available',
    body: 'You can now add family members to share compound access',
    type: 'system',
    read: true,
    timestamp: '2026-03-03T10:00:00',
  },
]

export const familyMembers: FamilyMember[] = [
  {
    id: 'fm1',
    name: 'Fatima Hassan',
    relation: 'Spouse',
    phone: '+20 100 234 5678',
    canInviteGuests: true,
    canAddVehicles: true,
    status: 'active',
  },
  {
    id: 'fm2',
    name: 'Omar Hassan',
    relation: 'Son',
    phone: '+20 101 345 6789',
    canInviteGuests: true,
    canAddVehicles: false,
    status: 'active',
  },
  {
    id: 'fm3',
    name: 'Nadia Hassan',
    relation: 'Daughter',
    phone: '+20 102 456 7890',
    canInviteGuests: false,
    canAddVehicles: false,
    status: 'pending',
  },
]

export const parkingSpots: ParkingSpot[] = [
  {
    id: 'ps1',
    number: 'B3-07',
    floor: 'B3',
    type: 'assigned',
    isOccupied: false,
  },
  {
    id: 'ps2',
    number: 'B3-08',
    floor: 'B3',
    type: 'assigned',
    isOccupied: true,
    vehicle: 'أ ب ج 1234',
    since: '2 hours ago',
  },
  {
    id: 'ps3',
    number: 'V-01',
    floor: 'Ground',
    type: 'visitor',
    isOccupied: true,
    vehicle: 'أ ب ج 5050',
    since: '45 min ago',
  },
  {
    id: 'ps4',
    number: 'V-02',
    floor: 'Ground',
    type: 'visitor',
    isOccupied: false,
  },
  {
    id: 'ps5',
    number: 'V-03',
    floor: 'Ground',
    type: 'visitor',
    isOccupied: false,
  },
]
